### ISSUE TITLE
TypeError in the Sudoku example

### ISSUE THREAD

**Issue by mexicer** [azreasoners/NeurASP#1]
Hi @zhunyoung @azreasoners ,

I tried to run the sudoku example as the instruction told, both `test.py` and `infer.py` reported `TypeError`, error stack shown as follow:

```
python test.py

Load the model trained with 15 data
/home/ubuntu/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448222085/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Test Acc Using Pure NN (whole board): 17.33%
Test Acc Using Pure NN (single cell): 98.02%
Oversubscription: #Threads=8 exceeds logical CPUs=4.
Traceback (most recent call last):
  File "/home/ubuntu/files/projects/disseration/NeurASP/examples/sudoku/test.py", line 54, in <module>
    acc = NeurASPobj.testInferenceResults(dataListTest, obsListTest)
  File "../../neurasp.py", line 439, in testInferenceResults
    models = self.infer(data, obs=':- mistake.', mvpp=self.mvpp['program_asp'])
  File "../../neurasp.py", line 224, in infer
    return dmvpp.find_one_most_probable_SM_under_obs_noWC(obs=obs)
  File "../../mvpp.py", line 204, in find_one_most_probable_SM_under_obs_noWC
    clingo_control.solve(None, lambda model: models.append(model.symbols(atoms=True)))
  File "/home/ubuntu/miniconda3/lib/python3.9/site-packages/clingo/control.py", line 574, in solve
    p_ass, len(assumptions),
TypeError: object of type 'NoneType' has no len()
```

```
python infer.py normal ./data/sudoku.png

Load the model trained with 25 instances of normal Sudoku puzzles
/home/ubuntu/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448222085/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Oversubscription: #Threads=8 exceeds logical CPUs=4.
Traceback (most recent call last):
  File "/home/ubuntu/files/projects/disseration/NeurASP/examples/sudoku/infer.py", line 91, in <module>
    models = NeurASPobj.infer(dataDic=dataDic, mvpp=rules[sudokuType])
  File "../../neurasp.py", line 224, in infer
    return dmvpp.find_one_most_probable_SM_under_obs_noWC(obs=obs)
  File "../../mvpp.py", line 204, in find_one_most_probable_SM_under_obs_noWC
    clingo_control.solve(None, lambda model: models.append(model.symbols(atoms=True)))
  File "/home/ubuntu/miniconda3/lib/python3.9/site-packages/clingo/control.py", line 574, in solve
    p_ass, len(assumptions),
TypeError: object of type 'NoneType' has no len()
```

Tried on both ubuntu and macos with python 3.9, same errors occured. 
Please help, thank you !

**Comment by azreasoners** [comment]
Thank you for letting us know about this issue. This error should be resolved by executing the following command to reinstall clingo with version 5.4. 
`conda install -c potassco clingo=5.4`
NeurASP was developed under clingo 5.4 (and works for clingo 5.3) while clingo has recently upgraded to 5.5 with some changes in their python API, which results in the error you've seen.

**Comment by petrichor1998** [comment]
I had the same issue while running the MNIST example code. Thanks for the clarification. Downgrading the version works.
